name: notebooks-environment
channels:
  - conda-forge
dependencies:
  - python=3
  - numpy
  - jupyterlab=0.35.1
  - pip
  - pip:
    - pandas
    - matplotlib
    - sklearn
    - seaborn
    - graphviz
