name: notebooks-environment
channels:
  - conda-forge
dependencies:
  - python=3.10
  - numpy
  - jupyterlab
  - pip
  - python-graphviz
  - graphviz
  - pip:
    - pandas
    - matplotlib
    - scikit-learn
    - seaborn
    - graphviz
