name: notebooks-environment
channels:
  - conda-forge
dependencies:
  - python
  - numpy
  - dot
  - graphviz
  - pip
  - pip:
    - pandas
    - matplotlib
    - sklearn
    - seaborn
    - graphviz
